const HomeProduct = [
  {
    id: 1,
    name: "Product 1",
    price: "19.99",
    image: "image/product-12.jpg",
    category: "tv",
    type: "new",
  },
  {
    id: 2,
    name: "Product 2",
    price: "29.99",
    image: "image/product-1.jpg",
    category: "laptop",
    type: "new",
  },
  {
    id: 3,
    name: "Product 3",
    price: "9.99",
    image: "image/product-6.png",
    category: "watch",
    type: "featured",
  },
  {
    id: 4,
    name: "Product 4",
    price: "49.99",
    image: "image/product-8.jpg",
    category: "headphone",
    type: "new",
  },
  {
    id: 5,
    name: "Product 5",
    price: "39.99",
    image: "image/product-3.png",
    category: "laptop",
    type: "new",
  },
  {
    id: 6,
    name: "Product 6",
    price: "15.99",
    image: "image/product-2.jpg",
    category: "laptop",
    type: "top",
  },
  {
    id: 7,
    name: "Product 7",
    price: "59.99",
    image: "image/product-11.jpg",
    category: "mobile",
    type: "featured",
  },
  {
    id: 8,
    name: "Product 8",
    price: "34.99",
    image: "image/product-4.png",
    category: "watch",
    type: "new",
  },
  {
    id: 9,
    name: "Product 9",
    price: "12.99",
    image: "image/product-5.png",
    category: "watch",
    type: "featured",
  },
  {
    id: 10,
    name: "Product 10",
    price: "79.99",
    image: "image/product-10.png",
    category: "electronics",
    type: "top",
  },
  {
    id: 11,
    name: "Product 11",
    price: "79.99",
    image: "image/product-7.png",
    category: "headphone",
    type: "new",
  },
  {
    id: 12,
    name: "Product 11",
    price: "79.99",
    image: "image/product-9.jpg",
    category: "electronics",
    type: "top",
  },
];

export default HomeProduct;
